# Generated by Django 5.1.1 on 2024-10-05 16:59

from django.db import migrations

def create_product_categories_and_attribute_categories_and_more(apps, schema_editor):
    def auto_set_category_path_on_change(instance):
        if not instance.parent:
            instance_path = f"/{instance.id}/"
        else:
            instance_path = instance.parent.path + f"{instance.id}/"
        
        instance.path=instance_path
        instance.save()

    # Категории продуктов
    ProductCategory = apps.get_model("products", "ProductCategory")
    category_electronics = ProductCategory(title="Эелктроника", assignable=False)
    category_electronics.save()
    auto_set_category_path_on_change(category_electronics)
    category_telephones_and_smart_watch = ProductCategory(title="Телефоны и смарт-часы", assignable=False, parent=category_electronics)
    category_telephones_and_smart_watch.save()
    auto_set_category_path_on_change(category_telephones_and_smart_watch)
    category_smartphones = ProductCategory(title="Смартфоны", assignable=True, parent=category_telephones_and_smart_watch)
    category_smartphones.save()
    auto_set_category_path_on_change(category_smartphones)

    # Категории атрибутов
    AttributeCategory = apps.get_model("products", "AttributeCategory")
    attribute_category_battery = AttributeCategory(title="Аккумулятор", category=category_smartphones)
    attribute_category_battery.save()
    attribute_category_camera = AttributeCategory(title="Камера", category=category_smartphones)
    attribute_category_camera.save()
    attribute_category_body = AttributeCategory(title="Корпус", category=category_smartphones)
    attribute_category_body.save()
    attribute_category_main = AttributeCategory(title="Основные", category=category_smartphones)
    attribute_category_main.save()
    attribute_category_screen = AttributeCategory(title="Экран", category=category_smartphones)
    attribute_category_screen.save()
    attribute_category_connection = AttributeCategory(title="Связь", category=category_smartphones)
    attribute_category_connection.save()
    attribute_category_memory_and_cpu = AttributeCategory(title="Память и процессор", category=category_smartphones)
    attribute_category_memory_and_cpu.save()
    attribute_category_sizes_and_weight = AttributeCategory(title="Габариты и вес", category=category_smartphones)
    attribute_category_sizes_and_weight.save()
    attribute_category_pecularities = AttributeCategory(title="Особенности", category=category_smartphones)
    attribute_category_pecularities.save()
    attribute_category_additional = AttributeCategory(title="Дополнительные", category=category_smartphones)
    attribute_category_additional.save()

    # Имена атрибутов
    AttributeName = apps.get_model("products", "AttributeName")
    attribute_name_accumulator_capacity = AttributeName(title="Емкость аккумулятора, мАч", attribute_category=attribute_category_battery)
    attribute_name_accumulator_capacity.save()
    attribute_name_accumulator_work_in_standby_mode = AttributeName(title="Работа в режиме ожидания, ч", attribute_category=attribute_category_battery)
    attribute_name_accumulator_work_in_standby_mode.save()
    attribute_name_accumulator_charging_functions = AttributeName(title="Функции зарядки", attribute_category=attribute_category_battery)
    attribute_name_accumulator_charging_functions.save()

    attribute_name_camera_1 = AttributeName(title="Разрешение основной камеры, Мпикс", attribute_category=attribute_category_camera)
    attribute_name_camera_1.save()
    attribute_name_camera_2 = AttributeName(title="Функции камеры", attribute_category=attribute_category_camera)
    attribute_name_camera_2.save()
    attribute_name_camera_3 = AttributeName(title="Количество основных камер", attribute_category=attribute_category_camera)
    attribute_name_camera_3.save()
    attribute_name_camera_4 = AttributeName(title="Разрешение фронтальной (селфи) камеры, Мпикс", attribute_category=attribute_category_camera)
    attribute_name_camera_4.save()
    attribute_name_camera_5 = AttributeName(title="Качество видео", attribute_category=attribute_category_camera)
    attribute_name_camera_5.save()
    attribute_name_camera_6 = AttributeName(title="Макс. скорость видеосъемки, кадр/с", attribute_category=attribute_category_camera)
    attribute_name_camera_6.save()


    attribute_name_body_1 = AttributeName(title="Интерфейсы", attribute_category=attribute_category_body)
    attribute_name_body_1.save()
    attribute_name_body_2 = AttributeName(title="Слот для карты памяти", attribute_category=attribute_category_body)
    attribute_name_body_2.save()
    attribute_name_body_3 = AttributeName(title="Тип корпуса", attribute_category=attribute_category_body)
    attribute_name_body_3.save()
    attribute_name_body_4 = AttributeName(title="Степень защиты", attribute_category=attribute_category_body)
    attribute_name_body_4.save()


    attribute_name_main_1 = AttributeName(title="Восстановленный", attribute_category=attribute_category_main)
    attribute_name_main_1.save()
    attribute_name_main_2 = AttributeName(title="Операционная система", attribute_category=attribute_category_main)
    attribute_name_main_2.save()

    attribute_name_screen_1 = AttributeName(title="Диагональ экрана, дюймы", attribute_category=attribute_category_screen)
    attribute_name_screen_1.save()
    attribute_name_screen_2 = AttributeName(title="Разрешение экрана", attribute_category=attribute_category_screen)
    attribute_name_screen_2.save()
    attribute_name_screen_3 = AttributeName(title="Технология матрицы", attribute_category=attribute_category_screen)
    attribute_name_screen_3.save()

    attribute_name_connection_1 = AttributeName(title="Беспроводные интерфейсы", attribute_category=attribute_category_connection)
    attribute_name_connection_1.save()
    attribute_name_connection_2 = AttributeName(title="Стандарты связи", attribute_category=attribute_category_connection)
    attribute_name_connection_2.save()
    attribute_name_connection_3 = AttributeName(title="Форм-фактор SIM", attribute_category=attribute_category_connection)
    attribute_name_connection_3.save()
    attribute_name_connection_4 = AttributeName(title="Число физических SIM-карт", attribute_category=attribute_category_connection)
    attribute_name_connection_4.save()
    attribute_name_connection_5 = AttributeName(title="Модуль связи Bluetooth", attribute_category=attribute_category_connection)
    attribute_name_connection_5.save()
    attribute_name_connection_6 = AttributeName(title="Модуль связи WiFi", attribute_category=attribute_category_connection)
    attribute_name_connection_6.save()
    attribute_name_connection_7 = AttributeName(title="Навигация", attribute_category=attribute_category_connection)
    attribute_name_connection_7.save()

    attribute_name_memory_and_cpu_1 = AttributeName(title="Процессор", attribute_category=attribute_category_memory_and_cpu)
    attribute_name_memory_and_cpu_1.save()
    attribute_name_memory_and_cpu_2 = AttributeName(title="Число ядер процессора", attribute_category=attribute_category_memory_and_cpu)
    attribute_name_memory_and_cpu_2.save()
    attribute_name_memory_and_cpu_3 = AttributeName(title="Оперативная память", attribute_category=attribute_category_memory_and_cpu)
    attribute_name_memory_and_cpu_3.save()
    attribute_name_memory_and_cpu_4 = AttributeName(title="Встроенная память", attribute_category=attribute_category_memory_and_cpu)
    attribute_name_memory_and_cpu_4.save()
    attribute_name_memory_and_cpu_5 = AttributeName(title="Тип карты памяти", attribute_category=attribute_category_memory_and_cpu)
    attribute_name_memory_and_cpu_5.save()
    attribute_name_memory_and_cpu_6 = AttributeName(title="Бренд процессора", attribute_category=attribute_category_memory_and_cpu)
    attribute_name_memory_and_cpu_6.save()
    attribute_name_memory_and_cpu_7 = AttributeName(title="Модель процессора", attribute_category=attribute_category_memory_and_cpu)
    attribute_name_memory_and_cpu_7.save()
    attribute_name_memory_and_cpu_8 = AttributeName(title="Частота процессора, ГГц", attribute_category=attribute_category_memory_and_cpu)
    attribute_name_memory_and_cpu_8.save()
    attribute_name_memory_and_cpu_9 = AttributeName(title="Бренд графического процессора", attribute_category=attribute_category_memory_and_cpu)
    attribute_name_memory_and_cpu_9.save()
    attribute_name_memory_and_cpu_10 = AttributeName(title="Видеопроцессор", attribute_category=attribute_category_memory_and_cpu)
    attribute_name_memory_and_cpu_10.save()
    attribute_name_memory_and_cpu_11 = AttributeName(title="Макс. объем карты памяти, ГБ", attribute_category=attribute_category_memory_and_cpu)
    attribute_name_memory_and_cpu_11.save()

    attribute_name_sizes_and_weight_1 = AttributeName(title="Размеры, мм", attribute_category=attribute_category_sizes_and_weight)
    attribute_name_sizes_and_weight_1.save()
    attribute_name_sizes_and_weight_2 = AttributeName(title="Вес товара, г", attribute_category=attribute_category_sizes_and_weight)
    attribute_name_sizes_and_weight_2.save()

    attribute_name_pecularities_1 = AttributeName(title="Аутентификация", attribute_category=attribute_category_pecularities)
    attribute_name_pecularities_1.save()
    attribute_name_pecularities_2 = AttributeName(title="Встроенные датчики", attribute_category=attribute_category_pecularities)
    attribute_name_pecularities_2.save()

    attribute_name_additional_1 = AttributeName(title="Артикул", attribute_category=attribute_category_additional)
    attribute_name_additional_1.save()
    attribute_name_additional_2 = AttributeName(title="Тип", attribute_category=attribute_category_additional)
    attribute_name_additional_2.save()
    attribute_name_additional_3 = AttributeName(title="Цвет", attribute_category=attribute_category_additional)
    attribute_name_additional_3.save()
    attribute_name_additional_4 = AttributeName(title="Гарантийный срок", attribute_category=attribute_category_additional)
    attribute_name_additional_4.save()
    attribute_name_additional_5 = AttributeName(title="Страна-изготовитель", attribute_category=attribute_category_additional)
    attribute_name_additional_5.save()

def remove_created_data(apps, schema_editor):
    ProductCategory = apps.get_model("products", "ProductCategory")
    ProductCategory.objects.all().delete()
    AttributeCategory = apps.get_model("products", "AttributeCategory")
    AttributeCategory.objects.all().delete()
    AttributeName = apps.get_model("products", "AttributeName")
    AttributeName.objects.all().delete()



class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_product_categories_and_attribute_categories_and_more, remove_created_data),
    ]
