# Generated by Django 5.1.1 on 2024-11-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20241005_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='published_at',
            field=models.DateTimeField(null=True, verbose_name='Опубликовано'),
        ),
    ]
